<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title><?= $this->e($title) ?></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"/>
    <style>
        body {
            padding-top: 70px;
        }

        .app {
            min-height: 100vh;
        }
    </style>
    <?= $this->section('stylesheets') ?>
</head>
<body class="app">
<div class="app-content">
    <main class="container">
        <?= $this->section('content') ?>
    </main>
</div>
<?= $this->section('javascript') ?>
</body>
</html>
